name: Test and Build

on:
  pull_request:
    branches:
      - main  # Ou o nome da sua branch principal

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build  
